### ISSUE TITLE
Meilenstein 1

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/Meilensteine#4]
Ich hab jetzt für den ersten Meilenstein einfach mal das Latex template gepusht.
Wie ihr sehr, habt ich das sehr stark aufgeteilt. In der Pflichtenheft.tex werden vor allem die Inputs aus den anderen .tex verwaltet.
In chapter/*.tex findet ihr dann die jeweiligen Dateien, in welche euer Stuff kommt

**Comment by ottojo** [comment]
# TODO:
* jeder muss seine TODOs erledigen
* Abhängigkeiten der FA setzen
* Jeder muss seine FAs noch sinnvoll anordnen (Reihenfolge)
* Deadline: 22:00

## @ottojo
- [x] Domänenmodell
### Server
- [x] 2.9: Gehört zum server (partie initialisieren)
- [x] 2.10: Server legt Zugreihenfolge am Anfang einer Runde fest
- [x] 2.12: Alternativen
- [x] Rundeninitialisierung
## Editor
- [x] 2.12: Unter "Werte und Wahrscheinlichkeiten", Wahrscheinlichkeiten nicht auflisten (fettgedruckt)

## @LukasBleile 
* [x] 2.6 (Cocktail verschütten)
* [x] 2.7 (Geheimnis als FA noch hinzufügen (genFA))

## @csacro 
* [x] 2.8 (Partievorbereitung, genFA)
* [x] 2.10.1 (Dauer eines Zuges)
* [x] 2.11: Ende der Partie

## @authaldo 
* [x] Fachwissen #2
